### PR TITLE
Convert times with the units package

### LINKED ISSUE #49: udunits2.h not checked/not found (openSUSE)
On openSUSE Tumbleweed, RNetCDF does not find the udunits header file. Configure log shows:
```
checking for library containing utFree... -ludunits2
checking udunits2/udunits.h usability... no
checking udunits2/udunits.h presence... no
checking for udunits2/udunits.h... no
checking udunits.h usability... no
checking udunits.h presence... no
checking for udunits.h... no
configure: error: "unable to use udunits2 or udunits"
```
On openSUSE it is available from the `udunits2-devel` package as `/usr/include/udunits2.h`. It looks like the configure script simply doesn't check for any header files with a `2` in it.

This is not an issue for the `udunits2` R package, that one installs fine, so a solution for this issue would also be to implement #12.

### PR DESCRIPTION
**Pull request by mjwoods**
Resolves #49 .

The original RNetCDF provided an interface to the udunits library, to allow conversion of time units (e.g. "hours since 1900-01-01") into calendar dates or other time units (e.g. "seconds since 1970-01-01"). Supporting the udunits interface across platforms and two major library versions is not trivial, and there are now several R packages that provide alternative udunits interfaces.

#49 reminded me about #12 , where the intention is to add support for the "units" package in RNetCDF. As a starting point, this pull request uses the units package for time conversions.

The new conversion routines provide the same R interface as the originals, but they may produce different results for calendar dates. Dates from the original routines were calculated entirely by udunits, but the new routines use the units package (and hence udunits) to convert time into POSIXct, then dates are derived by R. The calendars used by udunits and R may differ, but neither is necessarily more accurate. In particular, the [UDUNITS-2 C API Guide](https://www.unidata.ucar.edu/software/udunits/udunits-2.1.24/udunits2lib.html#Time) states:

> You should use a true calendar package rather than the UDUNITS-2 package to handle time. Having said that, many people use the time-handling capabilities of the UDUNITS-2 package because it supports "units" like "seconds since 1970-01-01". You should be aware, however, that the hybrid Gregorian/Julian calendar used by the UDUNITS-2 package cannot be changed.

In a similar spirit, the time conversions in RNetCDF are intended to provide a convenient way to handle time units within R. If the details of calendars are important for your application, it should be possible to use a specialised calendar package for date conversions in conjunction with the file operations provided by RNetCDF.

### CODE REVIEW

**Comment by edzer** [comment]
I think it is a good idea to move stuff that depends on udunit2 to the `units` package, to limit duplication and complexity.

But what would happen when using netcdf files that have time in a 360_day or 365_day / noleap callendar? Would the time information be converted into POSIXct, and if yes, how? When working with the [stars](https://github.com/r-spatial/stars) package we found that R package PCICt has dedicated support for non-POSIXct calendars found in netcdf (-CF) files. @kendonB @adrfantini https://github.com/r-spatial/stars/issues/135

**Comment by adrfantini** [comment]
As far as i know `PCICt` supports all kind of CF-Compliant calendars. Even `standard`, which is not listed in the manual. In a recent application I wrote for (future) production use, I decided to use `PCICt` for all `netCDF` calendars, and up to now nobody has complained or reported any bug.

However, to be fully honest, my usage of `PCICt` is up to now been limited to modern files, so I have not thoroughly tested sensitive things like the Julian/Gregorian transition.

**Comment by adrfantini** [comment]
Also, it has to be considered that `PCICt` seems somewhat of an abandoned project. The last [github](https://github.com/pacificclimate/PCICt) commit seems to be 5 years ago, even though the [CRAN version](https://github.com/cran/PCICt) seems to have been tweaked with recently.

**Comment by edzer** [comment]
(@adrfantini that is not the CRAN version you point to, but a mirror; the tweaked files concern auto-generated files, not activities by the authors of PCICt)

**Comment by adrfantini** [comment]
> (@adrfantini that is not the CRAN version you point to, but a mirror; the tweaked files concern auto-generated files, not activities by the authors of PCICt)

Oh, ok. Well, it has been published on CRAN on April 2018 so _sopmething_ must have been done around that time.

**Comment by edzer** [comment]
You're right; thanks!

**Comment by mjwoods** [comment]
Tempting as it is to support a variety of calendars, my goal here is to reimplement `utcal.nc` and `utinvcal.nc` without linking to the udunits C library (which adds many complications to RNetCDF, and is difficult to support properly). The units and udunits2 packages for R do not provide access to the calendar encoding/decoding functions of the udunits2 library, so I rely on R to convert between POSIXct and date-time elements.

I worry that this new implementation will not be good enough for some existing users of RNetCDF. As an alternative, perhaps the units or udunits2 packages could be extended to include date-time encoding/decoding functions. Or I could add a comment to the RNetCDF help files that recommends an alternative calendar package. What would you advise, @edzer and @adrfantini ?

**Comment by adrfantini** [comment]
> Tempting as it is to support a variety of calendars, my goal here is to reimplement `utcal.nc` and `utinvcal.nc` without linking to the udunits C library (which adds many complications to RNetCDF, and is difficult to support properly). The units and udunits2 packages for R do not provide access to the calendar encoding/decoding functions of the udunits2 library, so I rely on R to convert between POSIXct and date-time elements.
> 
> I worry that this new implementation will not be good enough for some existing users of RNetCDF. As an alternative, perhaps the units or udunits2 packages could be extended to include date-time encoding/decoding functions. Or I could add a comment to the RNetCDF help files that recommends an alternative calendar package. What would you advise, @edzer and @adrfantini ?

Sorry but I do not understand. `udunits2` does not provide calendar encoding/decoding functions, afaik. In fact [the docs](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Time) say:

> You should use a true calendar package rather than the UDUNITS-2 package to handle time. Having said that, many people use the time-handling capabilities of the UDUNITS-2 package because it supports "units" like "seconds since 1970-01-01". You should be aware, however, that the hybrid Gregorian/Julian calendar used by the UDUNITS-2 package cannot be changed. Dates on or after 1582-10-15 are assumed to be Gregorian dates; dates before that are assumed to be Julian dates. In particular, the year 1 BCE is immediately followed by the year 1 CE.

`units` can decode `udunits2`-formatted timestamps, but assuming R's calendar and ignoring the actual `netCDF` calendar attribute. As such, proper time handling in a netCDF file must, as of now, go through `PCICt`, which supports basic arithmetic operations on its calendars. It is sometimes (most of the times) possible to transform to `POSIXct`, of course, but you lose the correct interval length.

Thus, I think you do not _need_ `udunits` to convert times and dates - in fact, since calendars are not supported, you do not _want_ to use `udunits2` directly - unless you only care about Gregorian.

Imho `PCICt` support could be built into `utcal.nc` (maybe with a different name?), or alternatively into `units`, and `RNetCdf` could use `units` (which is something you would prefer to avoid, I understand).

I also think that `PCICt` is not the best solution right now, but it is the only one we have.

**Comment by Enchufa2** [comment]
To be precise:

- If the input is Julian-Gregorian, then you can feed it into `units`/`udunits2`. And more specifically, the method `as.POSIXct.units` that `units` provides will convert it into proleptic Gregorian, which is the calendar that base R supports.
- If the input is any other, you shouldn't use `units`/`udunits2` at all.

**Comment by mjwoods** [comment]
Sorry to disappoint everyone, but I've decided not to proceed with this pull request. My aim is to preserve the behaviour of RNetCDF calendar functions as far as possible. That implies continuing to use the udunits library functions for calendar conversions (`ut_encode_time` and `ut_decode_time`), because they use a hybrid Gregorian/Julian calendar which differs from the calendar in R. No other R packages provide an interface to udunits calendar functions, so direct linking from RNetCDF is still required.

I accept that udunits is not a proper calendar package, and I will recommend PCICt as a superior alternative. RNetCDF only provides calendar support for historical reasons, but I think it is important not to break existing applications that may depend on udunits calendars.

**Comment by edzer** [comment]
Fair decision. 

If we'd support these two functions in the `units` package, would you consider a PR that would use pkg `units` for the udunits stuff when 100% backward compatibility of RNetCDF would be retained?

**Comment by mjwoods** [comment]
If the `units` package provided the interfaces, I would definitely use them instead of linking udunits directly. Are you interested in having the calendar functions as part of `units`?

**Comment by edzer** [comment]
I think yes; I first need to understand them.

**Comment by Enchufa2** [comment]
What about a new package providing a wrapper around the complete udunits2 API? I have already an sketch of this using Rcpp in a branch in the `units` repo. I was planning to split this into a separate package, so that both `units` and `RNetCDF` can simply import from it.

**Comment by mjwoods** [comment]
I like that idea, @Enchufa2 . There is already a `udunits2` package, so could we contribute to that? Or is it better to start from scratch?

**Comment by Enchufa2** [comment]
Unfortunately, that package is not actively maintained anymore, so it's
better to start over.

**Comment by edzer** [comment]
I think `units` is pretty light-weight and nicely self-contained, I don't see much point in splitting it in two.

**Comment by Enchufa2** [comment]
There's one dependency anyways: Rcpp. But even if you prefer to link to udunits2 directly, it would be useful to have a package exposing the whole udunits2 API, and I don't think that's something `units` should do.

**Comment by edzer** [comment]
There you have a point. Maybe continue / open this discussion at the units repo?

**Pull request closed without merging**
